services:
  peptide-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peptide-compare-app
    restart: unless-stopped
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pepcomp.rule=Host(`pepcomp.thinkcraft.info`)"
      - "traefik.http.routers.pepcomp.entrypoints=websecure"
      - "traefik.http.routers.pepcomp.tls.certresolver=myresolver"
      - "traefik.http.services.pepcomp.loadbalancer.server.port=80"

networks:
  traefik_default:
    external: true
